added nginx platform config

diff --git a/workshop/workshop-java-repo/buildspec-owasp-zap.yml b/workshop/workshop-java-repo/buildspec-owasp-zap.yml
--- a/workshop/workshop-java-repo/buildspec-owasp-zap.yml
+++ b/workshop/workshop-java-repo/buildspec-owasp-zap.yml
@@ -34,8 +34,11 @@ phases:
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" zap-scan-results.json > payload.json
-        aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json owaspzap_scan_report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-      - if [ $high_alerts -gt 0 ] || [ $medium_alerts -gt 0 ]; then echo "there are high or medium alerts.. failing the build" && exit 1; else exit 0; fi
+      - if [ $high_alerts != 0 ]; then
+          echo "there are high alerts.. failing the build";
+          aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json owaspzap_scan_report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          exit 1; 
+        fi
 artifacts:
   type: zip
   files: '**/*'
